spring:
  application:
    name: spring-sec
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/second
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

bot:
  key: sasha

feign:
  url: http://194.87.237.31:8087

storage:
  url: src\\main\\resources\\static\\img